EFI-166
plancksecurity/iOS-planckForiOS pull request #13
Opened 2024-01-24 09:09 UTC by martinb89

2024-01-25 15:22 UTC, planckdz commented
Apart from the UI changes, the backend changes look way too much and complicated. Did we introduce bugs in the "special folders creation" that we never detected?

I was expecting a change in the create folders operation, an addition to the corresponding service for handling the other folders, plus a new constant.

What do we do here? Shall we split the ticket in the backend part (creating the special part) and the actual logic?

2024-01-25 15:22 UTC, planckdz requested changes

2024-01-25 15:22 UTC, planckdz commented on SubProjects/MessageModel/MessageModel/MessageModel/Interface/FetchImap/FetchImapFoldersService.swift
> +        func addOperationAndWait(blockingQueue: OperationQueue, operation: ImapSyncOperation) {
I really hope this extra blocking code is not needed. Why now?

2024-01-25 15:22 UTC, planckdz commented on SubProjects/MessageModel/MessageModel/MessageModel/Interface/FetchImap/FetchImapFoldersService.swift
> +        func addFolderCreationOperation(context: NSManagedObjectContext?, imapConnection: ImapConnection, blockingQueue: OperationQueue, folderType: FolderType) {
Add folders while fetching them? That doesn't sound right.

2024-01-25 15:29 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Interface/FetchImap/FetchImapFoldersService.swift
> +        func addFolderCreationOperation(context: NSManagedObjectContext?, imapConnection: ImapConnection, blockingQueue: OperationQueue, folderType: FolderType) {
Actually this is what fixes what we discuss yesterday. 
Here we create planck folder as well.

2024-01-25 15:30 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Interface/FetchImap/FetchImapFoldersService.swift
> +        func addOperationAndWait(blockingQueue: OperationQueue, operation: ImapSyncOperation) {
It's used. I just extracted duplicated code.

2024-01-26 08:05 UTC, planckdz approved these changes

2024-01-26 08:33 UTC, merged