Efi 174
plancksecurity/iOS-planckForiOS pull request #24
Opened 2024-02-27 15:41 UTC by martinb89

2024-02-28 15:03 UTC, planckdz requested changes

2024-02-28 15:03 UTC, ghost commented on pEpForiOS/UI/EmailDisplay/EmailDisplayList/EmailListViewController.swift
> +import MessageModel
Why is this import needed?

2024-02-28 15:03 UTC, ghost commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +    private func handleUI(sender: UIButton) {
Better name please than "handleUI".

2024-02-28 15:03 UTC, ghost commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +            let lineHeight: Double = 21.0
* Where are these magical numbers taken from? How would you know?
* In general, constants should stay close to where they are needed.

2024-02-28 15:03 UTC, ghost commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewModel.swift
> +        case cancel, decline, accept, changeLanguage, lenght
Typo

2024-02-28 15:03 UTC, ghost commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +        case 5:
For enum conversions, a switch is only good when there's no default. Otherwise, enum.(rawValue:).

2024-02-28 15:03 UTC, planckdz commented on pEpForiOS/UI/Util/Extensions/UILabel+Extension.swift
> +        let maxSize = CGSize(width: frame.size.width, height: CGFloat(Float.infinity))
CGFloat.greatestFiniteMagnitude

2024-03-04 08:30 UTC, martinb89 commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +    private func handleUI(sender: UIButton) {
Sure

2024-03-04 12:01 UTC, martinb89 commented on pEpForiOS/UI/EmailDisplay/EmailDisplayList/EmailListViewController.swift
> +import MessageModel
Removed, it was only for testing

2024-03-04 12:01 UTC, martinb89 commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +            let lineHeight: Double = 21.0
Now they are set only once as variables.

2024-03-04 12:01 UTC, martinb89 commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewModel.swift
> +        case cancel, decline, accept, changeLanguage, lenght
Fixed

2024-03-04 12:03 UTC, martinb89 commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +        case 5:
Will put an error and crash.

2024-03-04 12:03 UTC, martinb89 commented on pEpForiOS/UI/Util/Extensions/UILabel+Extension.swift
> +        let maxSize = CGSize(width: frame.size.width, height: CGFloat(Float.infinity))
Sure

2024-03-05 09:00 UTC, planckdz requested changes

2024-03-05 09:00 UTC, planckdz commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +    private func handleUI(sender: UIButton) {
Still there.

2024-03-05 09:00 UTC, planckdz commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +                Log.shared.errorAndCrash("Something wrong happend with the defaultHeightValue")
I don't see how this line can be reached, you checked it before.

2024-03-05 09:00 UTC, ghost commented on pEpForiOS/UI/KeySync/KeySyncHandshake/KeySyncHandshakeViewController.swift
> +                Log.shared.errorAndCrash("Something wrong happend with the defaultNumberOfLines")
This cannot be reached, you set it before. It can't be nil.

When dealing with optionals, you check once, then shadow in non-optionals and work with those.

2024-03-08 07:56 UTC, planckdz approved these changes

2024-03-08 09:59 UTC, merged