Efi 99
plancksecurity/iOS-planckForiOS pull request #3
Opened 2023-11-16 22:50 UTC by planckadmin

In GitLab by @mb on Oct 17, 2023, 17:26

2023-12-05 08:36 UTC, planckdz commented
Tests are not building.

2023-12-11 12:41 UTC, martinb89 commented
Tests are building now.

2023-12-12 08:42 UTC, planckdz requested changes

2023-12-12 09:17 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/AuditLoggingUtil.swift
> +    /// Save the event log (start, stop).
It was needed to add start and stop events. As discussed iirc, it was when the app enter in foreground and background or terminates.

2023-12-12 09:18 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/AuditLoggingUtil.swift
> +    func logEvent(maxLogTime: Int, auditLoggerEvent: AuditLoggerEvent, errorCallback: @escaping (Error) -> Void)
ok, maxNumberOfDays first.

2023-12-12 09:18 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/AuditLoggingUtil.swift
>  public enum AuditLoggerEvent: String {
It's not a general event.

2023-12-18 10:37 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/FileExportUtil.swift
> +            var newCsv: String
ok

2023-12-18 10:38 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/FileExportUtil.swift
> +                newCsv = me.createCSV(auditEventLog: auditEventLog,
It's used in :
me.prependSignatureAndSave(csv: newCsv, signature: signature, errorCallback: errorCallback)

2023-12-18 10:47 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/FileExportUtil.swift
> +                let signatureToVerify = me.extractSignatureFrom(csv: persistedCsvContent)
It's needed the signature and the content without the signature separately.

2023-12-18 14:07 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/FileExportUtil.swift
> +                PEPSession().verifyText(persistedCsvVersionWithoutSignature, signature: signatureToVerify) { error in
ok

2023-12-18 15:06 UTC, martinb89 commented on SubProjects/MessageModel/MessageModel/MessageModel/Util/FileExportUtil.swift
> +    private let beginPGP = "-----BEGIN PGP MESSAGE----"
Removed

2023-12-19 07:36 UTC, planckdz approved these changes

2023-12-19 09:45 UTC, merged